# Generated by Django 6.0.4 on 2026-04-22 11:47

import django.db.models.deletion
from django.db import migrations, models


def populate_existing_reports(apps, schema_editor):
    Report = apps.get_model("tasks", "Report")
    ReportStatusLog = apps.get_model("tasks", "ReportStatusLog")
    for index, report in enumerate(Report.objects.all().order_by("id"), start=1):
        year = 2026
        report.identifier = f"{year}-{index:03d}"
        if not report.what_happened:
            report.what_happened = report.description or report.title or "Sin descripcion inicial."
        if not report.when_happened:
            report.when_happened = "Fecha no especificada"
        report.status = "resolved" if report.done else "pending"
        report.save(
            update_fields=[
                "identifier",
                "what_happened",
                "when_happened",
                "status",
                "created_at",
                "updated_at",
            ]
        )
        ReportStatusLog.objects.create(
            report=report,
            status=report.status,
            note="Registro migrado desde el prototipo inicial de tareas.",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="Report",
        ),
        migrations.AddField(
            model_name="report",
            name="identifier",
            field=models.SlugField(blank=True, max_length=16, unique=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="category",
            field=models.CharField(
                choices=[
                    ("air_pollution", "Contaminacion del aire"),
                    ("water_pollution", "Contaminacion del agua"),
                    ("waste_dumping", "Vertimiento de residuos"),
                    ("deforestation", "Deforestacion"),
                    ("wildlife_trafficking", "Afectacion de fauna"),
                    ("noise_pollution", "Contaminacion auditiva"),
                    ("other", "Otro"),
                ],
                default="waste_dumping",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="other_category",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="report",
            name="what_happened",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="when_happened",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="report",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("in_review", "En revision"),
                    ("resolved", "Resuelto"),
                    ("rejected", "Rechazado"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="ReportImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="reports/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="tasks.report")),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportStatusLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pendiente"), ("in_review", "En revision"), ("resolved", "Resuelto"), ("rejected", "Rechazado")], max_length=24)),
                ("note", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_logs", to="tasks.report")),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.RunPython(
            code=populate_existing_reports,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="report",
            name="identifier",
            field=models.SlugField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-created_at"]},
        ),
    ]
